services:
  spark-pyspark:
    image: apache/spark-py
    container_name: spark-pyspark-container
    stdin_open: true
    tty: true
    user: root
    command: sh -c 'pip3 install pyspark && /opt/spark/bin/pyspark'
    ports:
      - 8081:4040
    environment:
      - PYSPARK_PYTHON=python3  # Define a versão do Python para PySpark, se necessário
      - SPARK_HOME=/opt/spark   # Define o diretório do Spark
      - PYTHONPATH=/opt/spark/python  # Adicione o diretório Python do Spark ao PYTHONPATH
    volumes:
      - ./:/opt/spark/work-dir